### PR TITLE
Fix CMake error being shown in the new Android Studio release

### PR DESCRIPTION
**Pull request by fzurita**
The error is preventing compilation on Android. This CMake change fixes the error.

Also fix build error when Android is not defined.

### CODE REVIEW

**Comment by Jj0YzL5nvJ** [comment]
Whoops... well, nothing breaks this time ^.^u

**Comment by ata4** [comment]
Thanks!

**Comment by fzurita** [comment]
Thank you, sorry to have broken then build with ANDROID not defined, i guess you must not build from master very often :)

**Comment by ata4** [comment]
Well, not from cmake at least. But CI/CD is on the todo list already. 😄

**Comment by Jj0YzL5nvJ** [comment]
I use CMake for shared DLL's, if you wish, I can make an AppVeyor file with both compilation methods.
That way the [WIP](#29) would no longer be necessary.

**Pull request merged**
