### PR TITLE
 Re-add check for valid dimensions in vi_process_start_fast

### PR DESCRIPTION
**Pull request by SigmaVirus**
Possible fix for #32

### CODE REVIEW

**Comment by twinaphex** [comment]
Have you tested this yourself? Didn't fix it for me.

**Comment by twinaphex** [comment]
Other games that appear to crash on startup on our libretro fork so far -

* Resident Evil 2/Biohazard 2
* Starcraft
* Stunt Racer

Do any of these issues happen to you guys too in the standalone plugin?

**Comment by ata4** [comment]
Well, I guess the check can be in `vi_process_start_fast` as well, even though the normal filter code doesn't seem to be affected. Also, twinaphex, I don't think that your issue is linked with this one, since this change would definitely fix it. I suspect it's an incompatibility with the mupen64plus API.

**Comment by loganmc10** [comment]
I tested about 6-8 of the games in that list (including KI Gold), no crashing in upstream mupen64plus

**Comment by twinaphex** [comment]
@loganmc10 The very same games work just fine with the other angrylion port though, so clearly there is an issue somewhere.

We found ways to make the performance divide with Linux/Mingw not as terrible BTW. You mind collaborating on this or do we need to keep this needless belligerent thing ongoing? Your call.

**Comment by SigmaVirus** [comment]
@twinaphex 

I don't know what you are talking about here but if you have followed the progress of the plugin and read issue #19 you would understand that these lines of codes fixes is a crash in Perfect Dark and possibly other games when using **Unfiltered output mode as saved startup value**

I didn't hear anyone complaining when ata4 first introduced this back then to fix #19 and I have a hard time believing that these few lines of code could cause major mayhem now.

@ata4 
Thanks for merging! 

@loganmc10 
Big thanks to you too, your builds of m64p are awesome however latest downloads (both x86 and x64) didn't include the angrylion plugin at all so I couldn't test this out.

**Comment by loganmc10** [comment]
@SigmaVirus thanks I didn't notice that, I'll open an issue

**Comment by loganmc10** [comment]
@SigmaVirus I posted an issue here: https://github.com/ata4/angrylion-rdp-plus/issues/34 really basic fix but I'm not at my computer now to submit a PR

**Comment by twinaphex** [comment]
@SigmaVirus It doesn't make any difference at all on my end - Perfect Dark still crashes at startup with or without these lines. That's what I was commenting on. I don't use upstream Mupen64plus because it's useless for my usecases, we have our own code.

It's not the fault of our Mupen64plus fork either because the old Angrylion plugin works just fine.

**Comment by SigmaVirus** [comment]
@twinaphex

OK there is no need to get upset here, I was just trying to re-fix an issue that was solved about a month ago that's all because I wanted to get Perfect Dark to work again with a specific output.

Obviously it works for Project64 and m64p but not for ParaLLEl-N64?

I know nothing about how angrylion works in the Libretro core and I don't claim to either.

Obviously this is all my fault, maybe it's just best that I stay the fuck out from things from now on but don't take this out on @ata4 because I think there could be a great teamwork!

**Comment by twinaphex** [comment]
I have no issues with you Sigmavirus, my issue is with loganmc10 who just cant let some self instigated beef go despite my best efforts to have us come to some kind of resolution. And honestly it has nothing to do with you and you should not get involvled. And frankly, at this point, I no longer want this guy posting in my timeline whenever I post somewhere, I already blocked the guy but apparently that is not enough for him to disappear. If this guy cannot bury the hatchet and he insists on stalking me around, pushing my buttons, ignoring any well intentioned truce I throw his way, and he has even admitted to just wanting. to irritate me, I might just have to resort to reporting this to Github and getting it done and over with. I want nothing to do with this toxic crap anymore, I have better stuff to do in my life than continue taking hits from some pathetic autists on the Internet, to be brutally fucking frank with you. Fuck this dude and the fucking horse he rode in on. Stop acting like a victim too. I gave you numerous chances here to let bygones be bygones and so we can return to some normalcy in our interactions, instead the dude just keeps up this irritating presence while being of zero help. Just like how he now sits in this thread and just ignores me and pretends I said nothing. I am done with this toxic personality, life is too short to deal with this guys bullshit, and maybe I just need to stop inflicting self harm on my mental wellbeing and just resort to reporting his repeated harrassment if he continues to keep this up.

**Comment by twinaphex** [comment]
@loganmc10  Yeah and then proceeding to ignore again my sincere call for a truce. You keep telling whatever bullshit you want to tell yourself, you know you are not being sincere. 

Honestly, I'm done with you. I no longer want to have some guy follow me around in threads that still keeps some beef going and doesn't want to resolve things, I want you out of my entire timeline. If 'blocking' people on Github doesn't do that, maybe I need to take it the extra mile and just start reporting you, maybe that will get the message to you delivered I am tired of this passive aggressive crap.

BTW, I have seen you admit on several outlets (4chan/reddit) that this is personal for you and you get a 'kick' out of irritating and harrassing me while you pretend to be innocent. I am done with this toxicity and crap, and I am putting you on notice right now that I will now act upon it if you continue keeping this up. If you don't want to resolve things, then stay out of my sight, you cannot have it both ways.

**Comment by SigmaVirus** [comment]
Wow, I just wanted to fix a crash for a game I love and it turned out like this.

I'm speechless and deeply saddened.....

I got no quarrels with either you @twinaphex, @loganmc10, @ata4 or anybody else for that matter.

I never knew things were this bad honestly.

**Comment by twinaphex** [comment]
@SigmaVirus Trust me, I have called numerous times for a truce with @loganmc10, there's only one person who keeps refusing and beating around the bush. The onus is on him to get his act together and start acting like an adult and let bygones be bygones.

**Comment by loganmc10** [comment]
I don't really understand what you mean by "truce"? I don't like you and have no interest in working with you, so I've tried to keep the interactions to a minimum and my comments short and on topic when dealing with you. I'm not sure what more you want.

**Comment by twinaphex** [comment]
What I want then is for you to piss off from my timeline and no longer appear wherever I am talking, and also to shut your mouth online about me. That is what I want, you 30+ year old Canuck autistic loser. Also, reimburse the money for that Shield hardware would be a nice gesture back. "I don't like you and have no interest in working with you" - yeah the dude who sent you that hardware whom I had to convince to send it to you because I wanted to show my appreciation for your work would be sure glad to know what the return on his investment back. Pathetic parasite.

Go fuck yourself with your sanctimonious bullshit, and BTW, next time I see you entering another thread again where I am around, you were unmentioned, and you keep this kind of 'prodding' along, I will report you. That I can assure you. I am about fed up with your constant vitriolic bullshit buddy.

**Comment by SigmaVirus** [comment]
It was probably for the best that he deleted his comments and left, I have never read such vulgar comments before, not in the emulation scene at least.

And @ata4 didn't deserve this kind of drama in his repository, it was disrespectful and unnecessary and there are other places where comments like that can be posted.

Boy, I'm surprised the humanity haven't extincted itself a long time ago and here we are on a GitHub page regarding emulation stuff and that's mildly.

@loganmc10 
I don't care at all what's been going on between you two and I don't take nobody's side either, you were the most polite and civil in this regard however which you deserves credit for.

**Comment by twinaphex** [comment]
I removed my comment and will be taking a safe distance from this point on to avoid any further conflict.

**Comment by twinaphex** [comment]
All those games are fixed now thanks to mudlord. So we no longer require any help, we did it ourselves.

**Pull request merged**
