### PR TITLE
CI/CD: Implement GitHub Actions and public nightly builds

### PR DESCRIPTION
**Pull request by Jj0YzL5nvJ**
This implementation has a small detail... it will be necessary to delete the `nightly-build` tag **from the local repository** as part of the build process to generate the correct version number.

[Check out my `nightly-build` for reference.](https://github.com/Jj0YzL5nvJ/angrylion-rdp-plus/releases/tag/nightly-build)
I needed to delete `nightly-build` and `v1.6-1` to generate the correct version number before the build process.

### CODE REVIEW

**Comment by ata4** [comment]
Thanks, that looks helpful. I was already trying to figure out the basics of Github Actions, this will save me a lot of work!

**Comment by Jj0YzL5nvJ** [comment]
The `nightly-build` tag is auto-generated, don't push said tag to github or you will duplicate the workflow unnecessarily.

**Comment by ata4** [comment]
The pipeline for Linux build exited with an error without the tag, though.

**Comment by Jj0YzL5nvJ** [comment]
Yeah... I theorized that error and wrote the logic so that the error didn't occur in `batch` but I forgot that `bash` would capture an error code with such logic.

**Pull request merged**
